# Generated by Django 5.1 on 2024-09-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('cid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=30)),
                ('seats', models.IntegerField()),
                ('roomno', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('sid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Subject_name', models.CharField(max_length=30)),
                ('sclass', models.CharField(max_length=50)),
                ('book', models.CharField(max_length=50)),
                ('steacher', models.CharField(max_length=50)),
                ('created_date', models.DateField()),
            ],
        ),
    ]
