# Generated by Django 5.1 on 2024-09-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_attendence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendence',
        ),
    ]
