# Generated by Django 5.1 on 2024-09-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='address',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='enquirydate',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='gender',
        ),
    ]
